import { FINISH_TYPE, PAINT_TYPE } from "./types";

export const commercialPaints: any = {
  tamiyaSpray: {
    name: "Tamiya Spray",
    value: "tamiyaSpray",
    paints: [
      {
        name: "Red Brown",
        color: "#6E5848",
        finish: FINISH_TYPE.MATTE,
        code: "TS-1",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Dark Green",
        color: "#384A3D",
        finish: FINISH_TYPE.MATTE,
        code: "TS-2",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Dark Yellow",
        color: "#AEA25B",
        finish: FINISH_TYPE.MATTE,
        code: "TS-3",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "German Gray",
        color: "#3A4548",
        finish: FINISH_TYPE.MATTE,
        code: "TS-4",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Olive Drab",
        color: "#4B5740",
        finish: FINISH_TYPE.MATTE,
        code: "TS-5",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Matte Black",
        color: "#181717",
        finish: FINISH_TYPE.MATTE,
        code: "TS-6",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Racing White",
        color: "#FFFFFF",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-7",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Italian Red",
        color: "#C73832",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-8",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "British Green",
        color: "#2A543D",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-9",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "French Blue",
        color: "#3E81B8",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-10",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Maroon",
        color: "#44323D",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-11",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Orange",
        color: "#D7813F",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-12",
        type: PAINT_TYPE.COMMERCIAL,
      },
      // {
      //   name: "Clear",
      //   color: "#FFFFFF",
      //   finish: FINISH_TYPE.GLOSS,
      //   code: "TS-13",
      //   type: PAINT_TYPE.COMMERCIAL,
      // },
      {
        name: "Black",
        color: "#181717",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-14",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Blue",
        color: "#224C88",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-15",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Yellow",
        color: "#F4ED55",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-16",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Gloss Aluminum",
        color: "#CAC9C8",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-17",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Metallic Red",
        color: "#C8354E",
        finish: FINISH_TYPE.METALLIC,
        code: "TS-18",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Metallic Blue",
        color: "#24538C",
        finish: FINISH_TYPE.METALLIC,
        code: "TS-19",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Metallic Green",
        color: "#489C53",
        finish: FINISH_TYPE.METALLIC,
        code: "TS-20",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Gold",
        color: "#C2AA49",
        finish: FINISH_TYPE.METALLIC,
        code: "TS-21",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Light Green",
        color: "#D1DB52",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-22",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Light Blue",
        color: "#4AA1D4",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-23",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Purple",
        color: "#4A4A79",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-24",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Pink",
        color: "#E0A9C1",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-25",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Pure White",
        color: "#FFFFFF",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-26",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Matte White",
        color: "#FFFFFF",
        finish: FINISH_TYPE.MATTE,
        code: "TS-27",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Olive Drab 2",
        color: "#45573E",
        finish: FINISH_TYPE.MATTE,
        code: "TS-28",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Semi-gloss Black",
        color: "#181717",
        finish: FINISH_TYPE.SEMIGLOSS,
        code: "TS-29",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Silver Leaf",
        color: "#CBD0CE",
        finish: FINISH_TYPE.METALLIC,
        code: "TS-30",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Bright Orange",
        color: "#CE5E37",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-31",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Haze Gray",
        color: "#607B7F",
        finish: FINISH_TYPE.MATTE,
        code: "TS-32",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Dull Red",
        color: "#7B4539",
        finish: FINISH_TYPE.MATTE,
        code: "TS-33",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Camel Yellow",
        color: "#E8B64A",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-34",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Park Green",
        color: "#469853",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-35",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Fluorescent Red",
        color: "#C53735",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-36",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Lavender",
        color: "#4E2C73",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-37",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Gunmetal",
        color: "#4D4E4D",
        finish: FINISH_TYPE.METALLIC,
        code: "TS-38",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Mica Red",
        color: "#A83332",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-39",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Metallic Black",
        color: "#323333",
        finish: FINISH_TYPE.METALLIC,
        code: "TS-40",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Coral Blue",
        color: "#51AC9E",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-41",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Light Gunmetal",
        color: "#727776",
        finish: FINISH_TYPE.METALLIC,
        code: "TS-42",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Racing Green",
        color: "#224633",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-43",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Brilliant Blue",
        color: "#29598D",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-44",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Pearl White",
        color: "#FFFFFF",
        finish: FINISH_TYPE.PEARL,
        code: "TS-45",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Light Sand",
        color: "#D1AC7C",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-46",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Chrome Yellow",
        color: "#F4DC4D",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-47",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Gunship Gray",
        color: "#5E757B",
        finish: FINISH_TYPE.MATTE,
        code: "TS-48",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Bright Red",
        color: "#C73832",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-49",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Mica Blue",
        color: "#273D76",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-50",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Racing Blue",
        color: "#263F79",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-51",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Candy Lime Green",
        color: "#59AA55",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-52",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Deep Metallic Blue",
        color: "#1B214B",
        finish: FINISH_TYPE.METALLIC,
        code: "TS-53",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Light Metallic Blue",
        color: "#356E90",
        finish: FINISH_TYPE.METALLIC,
        code: "TS-54",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Dark Blue",
        color: "#10263B",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-55",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Brilliant Orange",
        color: "#D7813F",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-56",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Blue Violet",
        color: "#5971A2",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-57",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Pearl Light Blue",
        color: "#7092B0",
        finish: FINISH_TYPE.PEARL,
        code: "TS-58",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Pearl Light Red",
        color: "#B28797",
        finish: FINISH_TYPE.PEARL,
        code: "TS-59",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Pearl Green",
        color: "#88BA9E",
        finish: FINISH_TYPE.PEARL,
        code: "TS-60",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Nato Green",
        color: "#3E513D",
        finish: FINISH_TYPE.MATTE,
        code: "TS-61",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Nato Brown",
        color: "#5E4D3C",
        finish: FINISH_TYPE.MATTE,
        code: "TS-62",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Nato Black",
        color: "#241A1D",
        finish: FINISH_TYPE.MATTE,
        code: "TS-63",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Dark Mica Blue",
        color: "#0F1C28",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-64",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Pearl Clear",
        color: "#FFFFFF",
        finish: FINISH_TYPE.PEARL,
        code: "TS-65",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "IJN Gray (Kure ARSN)",
        color: "#5C6970",
        finish: FINISH_TYPE.MATTE,
        code: "TS-66",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "IJN Gray (Sas ARSN)",
        color: "#454B53",
        finish: FINISH_TYPE.MATTE,
        code: "TS-67",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Wooden Deck Tan",
        color: "#A9A085",
        finish: FINISH_TYPE.MATTE,
        code: "TS-68",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Linoleum Deck Brown",
        color: "#544A3A",
        finish: FINISH_TYPE.MATTE,
        code: "TS-69",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Olive Drab (JGSDF)",
        color: "#3E513D",
        finish: FINISH_TYPE.MATTE,
        code: "TS-70",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Smoke",
        color: "#B2AFB0",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-71",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Clear Blue",
        color: "#4FABC1",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-72",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Clear Orange",
        color: "#D9873F",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-73",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Clear Red",
        color: "#C43079",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-74",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Champagne Gold",
        color: "#BDB691",
        finish: FINISH_TYPE.METALLIC,
        code: "TS-75",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Mica Silver",
        color: "#CAC9C8",
        finish: FINISH_TYPE.MATTE,
        code: "TS-76",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Flat Flesh 2",
        color: "#F2C38A",
        finish: FINISH_TYPE.MATTE,
        code: "TS-77",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Field Gray 2",
        color: "#526B55",
        finish: FINISH_TYPE.MATTE,
        code: "TS-78",
        type: PAINT_TYPE.COMMERCIAL,
      },
      // {
      //   name: "Semi-gloss Clear",
      //   color: "#FFFFFF",
      //   finish: FINISH_TYPE.SEMIGLOSS,
      //   code: "TS-79",
      //   type: PAINT_TYPE.COMMERCIAL,
      // },
      // {
      //   name: "Flat Clear",
      //   color: "#FFFFFF",
      //   finish: FINISH_TYPE.MATTE,
      //   code: "TS-80",
      //   type: PAINT_TYPE.COMMERCIAL,
      // },
      {
        name: "Royal Light Gray",
        color: "#C0CBC4",
        finish: FINISH_TYPE.MATTE,
        code: "TS-81",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Black Rubber",
        color: "#40454A",
        finish: FINISH_TYPE.MATTE,
        code: "TS-82",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Metallic Silver",
        color: "#B5BAC2",
        finish: FINISH_TYPE.METALLIC,
        code: "TS-83",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Metallic Gold",
        color: "#BCAE58",
        finish: FINISH_TYPE.METALLIC,
        code: "TS-84",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Bright Mica Red Ferrari",
        color: "#B43430",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-85",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Brilliant Red",
        color: "#D13733",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-86",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Titanium Gold",
        color: "#CFBF98",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-87",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Titanium Silver",
        color: "#D3D5C8",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-88",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Pearl Blue",
        color: "#211E5A",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-89",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Brown (JGSDF)",
        color: "#7D663B",
        finish: FINISH_TYPE.MATTE,
        code: "TS-90",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Dark Green (JGSDF)",
        color: "#2D5F42",
        finish: FINISH_TYPE.MATTE,
        code: "TS-91",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Metallic Orange",
        color: "#E47C3A",
        finish: FINISH_TYPE.METALLIC,
        code: "TS-92",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Pure Blue",
        color: "#255499",
        finish: FINISH_TYPE.GLOSS,
        code: "TS-93",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Metallic Gray",
        color: "#514E48",
        finish: FINISH_TYPE.METALLIC,
        code: "TS-94",
        type: PAINT_TYPE.COMMERCIAL,
      },
    ],
  },
  citadelColourCitadel: {
    name: "Citadel Colour Citadel",
    value: "citadelColourCitadel",
    paints: [
      {
        name: "Sunburst Yellow",
        color: "#FFEB3B",
        finish: FINISH_TYPE.DEFAULT,
        code: "citadel1",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Goldenrod",
        color: "#FFC107",
        finish: FINISH_TYPE.DEFAULT,
        code: "citadel2",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Amber",
        color: "#FF9800",
        finish: FINISH_TYPE.DEFAULT,
        code: "citadel3",
        type: PAINT_TYPE.COMMERCIAL,
      },
    ],
  },
  acrylicosVallejoVallejoMechaColor: {
    name: "Acrylicos Vallejo Vallejo Mecha Color",
    value: "acrylicosVallejoVallejoMechaColor",
    paints: [
      {
        name: "Bright Red",
        color: "#FF5252",
        finish: FINISH_TYPE.DEFAULT,
        code: "vallejo1",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Neon Green",
        color: "#69F0AE",
        finish: FINISH_TYPE.DEFAULT,
        code: "vallejo2",
        type: PAINT_TYPE.COMMERCIAL,
      },
      {
        name: "Vivid Blue",
        color: "#448AFF",
        finish: FINISH_TYPE.DEFAULT,
        code: "vallejo3",
        type: PAINT_TYPE.COMMERCIAL,
      },
    ],
  },
};
