import {
  ALPHA_MODE,
  FINISH_TYPE,
  MaterialData,
  PAINT_TYPE,
  Part,
} from "./types";

export const parts: Part[] = [
  {
    slug: "head",
    label: "Head",
    materials: [
      ["head.monoeye", "Monoeye"],
      ["head.armor.1", "Armor 1"],
      ["head.armor.2", "Armor 2"],
      ["head.armor.3", "Armor 3"],
      ["head.accents", "Accents 1"],
      ["head.accents.2", "Accents 2"],
      ["head.accents.3", "Accents 3"],
      ["head.helmet.end", "Accents 4"],
      ["head.inner.2", "Inner Frame 3"],
      ["head.inner.3", "Inner Frame 2"],
    ],
  },
  {
    slug: "torso",
    label: "Torso",
    materials: [
      ["torso.armor.1", "Armor 1"],
      ["torso.armor.2", "Armor 2"],
      ["torso.armor.3", "Armor 3"],
      ["torso.accents", "Accents 1"],
      ["torso.accents.2", "Accents 2"],
      ["torso.inner", "Inner Frame 1"],
      ["torso.inner.2", "Inner Frame 2"],
      ["torso.inner.3", "Inner Frame 3"],
      ["torso.inner.4", "Inner Frame 4"],
      ["torso.inner.5", "Inner Frame 5"],
      ["torso.inner.6", "Inner Frame 6"],
      ["torso.tubes", "Tubes"],
    ],
  },
  {
    slug: "waist",
    label: "Waist",
    materials: [
      ["waist.armor.1", "Armor 1"],
      ["waist.armor.2", "Armor 2"],
      ["waist.armor.3", "Armor 3"],
      ["waist.accents", "Accents 1"],
      ["waist.accents.2", "Accents 2"],
      ["waist.accents.3", "Accents 3"],
      ["waist.inner", "Inner Frame 1"],
      ["waist.inner.2", "Inner Frame 2"],
      ["waist.thrusters", "Thrusters"],
      ["waist.tubes", "Tubes 1"],
      ["waist.tubes.3", "Tubes 2"],
    ],
  },
  {
    slug: "shoulders",
    label: "Shoulders",
    materials: [
      ["shoulders.armor.1", "Armor 1"],
      ["shoulders.armor.2", "Armor 2"],
      ["shoulders.armor.3", "Armor 3"],
      ["shoulders.armor.4", "Armor 4"],
      ["shoulders.accents", "Accents 1"],
      ["shoulders.accents.001", "Accents 2"],
      ["shoulders.accents.002", "Accents 3"],
      ["shoulders.yellow", "Accent 4"],
      ["shoulders.inner", "Inner Frame"],
      ["shoulders.thrusters", "Thrusters"],
      ["shoulders.tubes", "Tubes"],
    ],
  },
  {
    slug: "arms",
    label: "Arms",
    materials: [
      ["arms.armor", "Armor 1"],
      ["arms.armor.001", "Armor 2"],
      ["arms.armor.002", "Armor 3"],
      ["arms.accents", "Accents"],
      ["arms.inner", "Inner Frame 1"],
      ["arms.inner.002", "Inner Frame 2"],
      ["arms.inner.003", "Inner Frame 3"],
      ["arms.hands", "Hands"],
      ["arms.tubes", "Tubes"],
    ],
  },
  {
    slug: "legs",
    label: "Legs",
    materials: [
      ["legs.accents", "Accents 1"],
      ["legs.accents.001", "Accents 2"],
      ["legs.armor", "Armor 1"],
      ["legs.armor.001", "Armor 2"],
      ["legs.armor.002", "Armor 3"],
      ["legs.armor.003", "Armor 4"],
      ["legs.inner", "Inner Frame 1"],
      ["legs.inner.001", "Inner Frame 2"],
      ["legs.tubes", "Tubes"],
    ],
  },
  {
    slug: "backpack",
    label: "Backpack",
    materials: [
      ["backpack.accents", "Accents 1"],
      ["backpack.accents.001", "Accents 2"],
      ["backpack.yellow", "Accents 3"],
      ["backpack.funnels", "Funnels"],
      ["backpack.inner", "Inner Frame 1"],
      ["backpack.inner.001", "Inner Frame 2"],
      ["backpack.main", "Main 1"],
      ["backpack.main.001", "Main 2"],
      ["backpack.rings", "Rings"],
      ["backpack.thrusters", "Thrusters 1"],
      ["backpack.thrusters.001", "Thrusters 2"],
    ],
  },
  {
    slug: "frame",
    label: "Inner Frame",
    materials: [["frame", "Inner Frame"]],
  },
];

export const sazabiMaterialsMap: Record<string, MaterialData> = {
  "arms.accents": {
    color: "#853f00",
    paint: {
      color: "#853f00",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "arms.armor": {
    color: "#c60606",
    paint: {
      color: "#c60606",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "arms.armor.001": {
    color: "#790404",
    paint: {
      color: "#790404",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "arms.armor.002": {
    color: "#cf1818",
    paint: {
      color: "#cf1818",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "arms.hands": {
    color: "#101212",
    paint: {
      color: "#101212",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "arms.inner": {
    color: "#101010",
    paint: {
      color: "#101010",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "arms.inner.002": {
    color: "#050505",
    paint: {
      color: "#050505",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "arms.inner.003": {
    color: "#0a0a0a",
    paint: {
      color: "#0a0a0a",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "arms.tubes": {
    color: "#969696",
    paint: {
      color: "#969696",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "backpack.accents": {
    color: "#ffd3d3",
    paint: {
      color: "#ffd3d3",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "backpack.accents.001": {
    color: "#853f00",
    paint: {
      color: "#853f00",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "backpack.funnels": {
    color: "#c60606",
    paint: {
      color: "#c60606",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "backpack.inner": {
    color: "#8b8b8b",
    paint: {
      color: "#8b8b8b",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "backpack.inner.001": {
    color: "#969696",
    paint: {
      color: "#969696",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "backpack.main": {
    color: "#050505",
    paint: {
      color: "#050505",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "backpack.main.001": {
    color: "#050505",
    paint: {
      color: "#050505",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "backpack.rings": {
    color: "#e4e4e4",
    paint: {
      color: "#e4e4e4",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "backpack.thrusters": {
    color: "#050505",
    paint: {
      color: "#050505",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "backpack.thrusters.001": {
    color: "#e4e4e4",
    paint: {
      color: "#e4e4e4",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "backpack.yellow": {
    color: "#ff8200",
    paint: {
      color: "#ff8200",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  frame: {
    color: "#101212",
    paint: {
      color: "#101212",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "head.accents": {
    color: "#853f00",
    paint: {
      color: "#853f00",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "head.accents.2": {
    color: "#00ffff",
    paint: {
      color: "#00ffff",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "head.accents.3": {
    color: "#ffffff",
    paint: {
      color: "#ffffff",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "head.armor.1": {
    color: "#c60606",
    paint: {
      color: "#c60606",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "head.armor.2": {
    color: "#cf1818",
    paint: {
      color: "#cf1818",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "head.armor.3": {
    color: "#790404",
    paint: {
      color: "#790404",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "head.helmet.end": {
    color: "#e4e4e4",
    paint: {
      color: "#e4e4e4",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "head.inner.2": {
    color: "#969696",
    paint: {
      color: "#969696",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "head.inner.3": {
    color: "#8b8b8b",
    paint: {
      color: "#8b8b8b",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "head.monoeye": {
    color: "#ddfff4",
    paint: {
      color: "#ddfff4",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "legs.accents": {
    color: "#e4e4e4",
    paint: {
      color: "#e4e4e4",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "legs.accents.001": {
    color: "#853f00",
    paint: {
      color: "#853f00",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "legs.armor": {
    color: "#790404",
    paint: {
      color: "#790404",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "legs.armor.001": {
    color: "#c60606",
    paint: {
      color: "#c60606",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "legs.armor.002": {
    color: "#cf1818",
    paint: {
      color: "#cf1818",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "legs.armor.003": {
    color: "#c60606",
    paint: {
      color: "#c60606",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "legs.inner": {
    color: "#8b8b8b",
    paint: {
      color: "#8b8b8b",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "legs.inner.001": {
    color: "#050505",
    paint: {
      color: "#050505",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "legs.tubes": {
    color: "#969696",
    paint: {
      color: "#969696",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "shoulders.accents": {
    color: "#853f00",
    paint: {
      color: "#853f00",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "shoulders.accents.001": {
    color: "#e4e4e4",
    paint: {
      color: "#e4e4e4",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "shoulders.accents.002": {
    color: "#ffd3d3",
    paint: {
      color: "#ffd3d3",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "shoulders.armor.1": {
    color: "#790404",
    paint: {
      color: "#790404",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "shoulders.armor.2": {
    color: "#cf1818",
    paint: {
      color: "#cf1818",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "shoulders.armor.3": {
    color: "#c60606",
    paint: {
      color: "#c60606",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "shoulders.armor.4": {
    color: "#c60606",
    paint: {
      color: "#c60606",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "shoulders.inner": {
    color: "#969696",
    paint: {
      color: "#969696",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "shoulders.thrusters": {
    color: "#8b8b8b",
    paint: {
      color: "#8b8b8b",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "shoulders.tubes": {
    color: "#ff8200",
    paint: {
      color: "#ff8200",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "shoulders.yellow": {
    color: "#ff8200",
    paint: {
      color: "#ff8200",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "torso.accents": {
    color: "#00ffff",
    paint: {
      color: "#00ffff",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "torso.accents.2": {
    color: "#ff8200",
    paint: {
      color: "#ff8200",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "torso.armor.1": {
    color: "#790404",
    paint: {
      color: "#790404",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "torso.armor.2": {
    color: "#cf1818",
    paint: {
      color: "#cf1818",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "torso.armor.3": {
    color: "#c60606",
    paint: {
      color: "#c60606",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "torso.inner": {
    color: "#969696",
    paint: {
      color: "#969696",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "torso.inner.2": {
    color: "#ffd3d3",
    paint: {
      color: "#ffd3d3",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "torso.inner.3": {
    color: "#dddddd",
    paint: {
      color: "#dddddd",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "torso.inner.4": {
    color: "#050505",
    paint: {
      color: "#050505",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "torso.inner.5": {
    color: "#8b8b8b",
    paint: {
      color: "#8b8b8b",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "torso.inner.6": {
    color: "#101010",
    paint: {
      color: "#101010",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "torso.tubes": {
    color: "#853f00",
    paint: {
      color: "#853f00",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "waist.accents": {
    color: "#ff8200",
    paint: {
      color: "#ff8200",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "waist.accents.2": {
    color: "#e4e4e4",
    paint: {
      color: "#e4e4e4",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "waist.accents.3": {
    color: "#ffd3d3",
    paint: {
      color: "#ffd3d3",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "waist.armor.1": {
    color: "#790404",
    paint: {
      color: "#790404",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "waist.armor.2": {
    color: "#cf1818",
    paint: {
      color: "#cf1818",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "waist.armor.3": {
    color: "#c60606",
    paint: {
      color: "#c60606",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "waist.inner": {
    color: "#873b08",
    paint: {
      color: "#873b08",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "waist.inner.2": {
    color: "#969696",
    paint: {
      color: "#969696",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "waist.thrusters": {
    color: "#8b8b8b",
    paint: {
      color: "#8b8b8b",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "waist.tubes": {
    color: "#853f00",
    paint: {
      color: "#853f00",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
  "waist.tubes.3": {
    color: "#8c58e1",
    paint: {
      color: "#8c58e1",
      name: "",
      finish: FINISH_TYPE.DEFAULT,
      type: PAINT_TYPE.OWN,
    },
    isClear: false,
    finish: FINISH_TYPE.DEFAULT,
    alphaMode: ALPHA_MODE.OPAQUE,
  },
};
